import {rpc,signin,logout} from './api.mjs';
const app=document.querySelector('#app'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const brand='<div class="brand"><img src="logo.svg" alt="OneHome logo">One<span>Home</span></div>';
let mode='student',data=null,view='home',code='',active=null,qn=0,dirty=false,confirmSubmit=false,reportId=null,topicSubject='Maths',search='';
const name=p=>[p?.first,p?.last].filter(Boolean).join(' ')||'Student';
const cls=id=>data.classes.find(c=>c.id===id)?.name||'Former class';
const progress=(id,studentId)=>data.progress.find(p=>p.assignment_id===id&&(!studentId||p.student_id===studentId));
const date=v=>new Date(v).toLocaleString('en-GB',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});
const due=a=>new Date(a.due_at)<new Date();
function toast(s){const t=document.querySelector('#toast');t.textContent=s;t.className='show';setTimeout(()=>t.className='',5500)}
async function run(el,fn){if(el)el.disabled=true;try{await fn()}catch(e){toast(e.message)}finally{if(el?.isConnected)el.disabled=false}}
const empty=t=>`<div class="empty">${esc(t)}</div>`;
function login(error=''){
app.innerHTML=`<div class="login"><section class="intro">${brand}<h1>A little practice.<br><em>A big difference.</em></h1><p>Your homework, your next step. Build confidence in Maths, Reading and Science, one question at a time.</p><div class="mini-grid"><div><b>÷</b>Maths</div><div><b>Aa</b>Reading</div><div><b>⚗</b>Science</div></div></section><section class="signin"><form id="login"><div class="switch"><button type="button" data-mode="student" class="${mode==='student'?'selected':''}">Student</button><button type="button" data-mode="staff" class="${mode==='staff'?'selected':''}">Staff</button></div><span class="eyebrow">WELCOME TO ONEHOME</span><h1>${mode==='staff'?'Less setting.<br>More learning.':'Ready when you are.'}</h1><p class="muted">${mode==='staff'?'Use your existing OneEducation staff account. Your classes are already connected.':'Use the same private student code as your OneEducation portal.'}</p>${mode==='staff'?'<label for="email">Staff email</label><input id="email" type="email" autocomplete="username" required><label for="password">Password</label><input id="password" type="password" autocomplete="current-password" required>':'<label for="code">Your student code</label><input id="code" autocomplete="off" spellcheck="false" placeholder="Paste your OneEducation code" required>'}<button class="full" type="submit">${mode==='staff'?'Sign in to staff workspace':'Let’s get started'} →</button><p id="loginError" class="error" role="alert">${esc(error)}</p><p class="footnote">OneHome · Part of One Education<br>School staff can help if you need your login details.</p></form></section></div>`;
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;login()});
document.querySelector('#login').onsubmit=async e=>{e.preventDefault();e.submitter.disabled=true;try{if(mode==='staff'){data=await signin(document.querySelector('#email').value.trim(),document.querySelector('#password').value)}else{code=document.querySelector('#code').value.trim();data=await rpc('oh_student',{p_code:code});sessionStorage.setItem('onehome-code',code)}view='home';render()}catch(err){document.querySelector('#loginError').textContent=err.message;e.submitter.disabled=false}};
}
async function refresh(){data=await rpc(mode==='staff'?'oh_staff':'oh_student',mode==='staff'?{}:{p_code:code},mode==='staff');render()}
function head(title,copy,button=''){return `<header class="pagehead"><div><span class="eyebrow">${mode==='staff'?'TEACHER WORKSPACE':'YOUR LEARNING SPACE'}</span><h1>${title}</h1><p>${copy}</p></div>${button}</header>`}
function stats(items){return `<div class="stats">${items.map(([label,value])=>`<div class="stat"><small>${label}</small><strong>${value}</strong></div>`).join('')}</div>`}
function render(){const nav=mode==='staff'?[['home','Overview'],['homework','Homework'],['topics','Topic library'],['results','Class progress']]:[['home','My home'],['homework','My homework'],['completed','My results']];app.innerHTML=`<div class="shell"><aside>${brand}<nav>${nav.map(([id,label])=>`<button data-nav="${id}" class="${view===id?'active':''}">${label}</button>`).join('')}</nav><div class="rail-note"><strong>Connected to One Education</strong><br>${mode==='staff'?'Classes and pupils come from your saved MIS records.':'Small steps. Stronger understanding.'}</div></aside><div class="workspace"><header class="topbar"><div><strong>${esc(data.school?.name||'OneHome')}</strong><small>${mode==='staff'?'Homework & learning':`Year ${esc(data.student.year)} · Student workspace`}</small></div><div class="actions"><span class="avatar">${mode==='staff'?'T':esc(data.student.first?.[0]||'S')}</span><button class="plain" id="refresh">Refresh</button><button class="plain" id="logout">Sign out</button></div></header><main class="content">${active?questionPage():mode==='staff'?staffPage():studentPage()}</main></div></div>`;
document.querySelectorAll('[data-nav]').forEach(b=>b.onclick=()=>run(b,async()=>{if(active&&dirty)await saveDraft();active=null;view=b.dataset.nav;render()}));
document.querySelector('#logout').onclick=()=>{if(dirty&&!confirm('You have unsaved answers. Sign out and discard them?'))return;logout();data=null;active=null;dirty=false;code='';login()};
document.querySelector('#refresh').onclick=e=>run(e.currentTarget,async()=>{if(active){if(dirty)await saveDraft();active=await rpc('oh_open',{p_code:code,p_id:active.assignment.id});render()}else await refresh()});
bind();}
function studentCard(a){const p=progress(a.id),done=!!p?.submitted_at,answered=done?a.question_ids.length:0;return `<article class="card"><div class="card-head"><span class="tag ${done?'done':due(a)?'late':''}">${done?'Completed':due(a)?'Overdue':p?'In progress':'Ready to start'}</span><small>${a.question_ids.length} questions</small></div><h3>${esc(a.title)}</h3><p>${esc(cls(a.class_id))}</p>${done?`<div class="bar"><span style="width:${100*p.score/a.question_ids.length}%"></span></div><p><strong>${p.score} / ${a.question_ids.length}</strong> correct · submitted ${date(p.submitted_at)}</p>`:`<p>Due ${date(a.due_at)}</p>`}<div class="card-foot"><small>${done?'Feedback ready':'Save your progress as you go'}</small><button data-open="${a.id}">${done?'See feedback':p?'Continue':'Start homework'} →</button></div></article>`}
function studentPage(){const all=data.assignments,pending=all.filter(a=>!progress(a.id)?.submitted_at),complete=all.filter(a=>progress(a.id)?.submitted_at);if(view==='completed')return head('Look how far you’ve come.','Your completed work and question-by-question feedback.')+(complete.length?`<div class="grid">${complete.map(studentCard).join('')}</div>`:empty('Your results will appear after you submit your first homework.'));if(view==='homework')return head('Your next steps.','Work through your homework at your own pace. Late work can still be submitted.')+(pending.length?`<div class="grid">${pending.map(studentCard).join('')}</div>`:empty('You’re all caught up. New homework will appear here when your teachers set it.'));return head(`Hello, ${esc(data.student.first||'there')}.`,'Let’s make a little progress today.')+`<section class="hero"><div><span class="eyebrow">MAKE TODAY COUNT</span><h2>Confidence starts with practice.</h2><p>Pick a homework, take your time, and use the hints when you need a nudge.</p></div><div class="hero-mark">a²+b²</div></section>`+stats([['To complete',pending.length],['Completed',complete.length],['My classes',data.classes.length]])+`<div class="pagehead"><h2>Up next</h2><small>Closest deadlines first</small></div>`+(pending.length?`<div class="grid">${pending.slice(0,4).map(studentCard).join('')}</div>`:empty('No homework waiting. A good moment to take a break.'));}
function staffCard(a){const roster=data.students.filter(s=>s.classIds.includes(a.class_id)),done=roster.filter(s=>progress(a.id,s.id)?.submitted_at).length;return `<article class="card"><div class="card-head"><span class="tag">${a.archived?'Archived':'Published'}</span><small>${a.question_ids.length} questions</small></div><h3>${esc(a.title)}</h3><p>${esc(cls(a.class_id))} · Due ${date(a.due_at)}</p><div class="bar"><span style="width:${roster.length?100*done/roster.length:0}%"></span></div><div class="card-foot"><small>${done} / ${roster.length} submitted</small><button class="secondary" data-report="${a.id}">View progress</button>${a.archived?'':`<button class="plain" data-archive="${a.id}">Archive</button>`}</div></article>`}
function staffPage(){const all=data.assignments.filter(a=>!a.archived);if(view==='create')return createPage();if(view==='report')return reportPage();if(view==='topics')return topicPage();if(view==='results')return head('A clearer picture.','Completion and scores for your current class memberships.')+(data.assignments.length?`<div class="grid">${data.assignments.map(staffCard).join('')}</div>`:empty('Create your first homework to start tracking progress.'));if(view==='homework')return head('Homework, handled.','Ready-made topics. Automatically assembled and marked.',`<button data-create>+ Create homework</button>`)+(all.length?`<div class="grid">${all.map(staffCard).join('')}</div>`:empty('No active homework. Create one using the topic library.'));return head('A good day to make progress.','Your school’s homework, together in one place.',`<button data-create>+ Create homework</button>`)+`<section class="hero"><div><span class="eyebrow">LESS ADMIN. MORE LEARNING.</span><h2>You pick the topics.<br>OneHome builds the homework.</h2><p>Choose a class, select the skills, and set a deadline. Questions and marking are ready to go.</p></div><div class="hero-mark">✦</div></section>`+stats([['Connected students',data.students.length],['Active homework',all.length],['Ready-made topics',data.topics.length]])+`<div class="pagehead"><h2>Recently set</h2><small>Live from your school</small></div>`+(all.length?`<div class="grid">${all.slice(0,4).map(staffCard).join('')}</div>`:empty('Your first assignment starts here. Select “Create homework”.'));}
function topicPage(){const ts=data.topics.filter(t=>t.subject===topicSubject&&t.title.toLowerCase().includes(search.toLowerCase()));return head('A library of next steps.','Original questions, hints and explanations. Choose the level that fits your class.')+`<div class="filters"><select id="topicSubject">${['Maths','Reading','Science'].map(s=>`<option ${s===topicSubject?'selected':''}>${s}</option>`).join('')}</select><input id="topicSearch" placeholder="Find a topic…" value="${esc(search)}"></div><div class="grid">${ts.map(t=>`<article class="card"><div class="card-head"><span class="tag ${t.subject}">${t.subject}</span><small>${t.count} questions</small></div><h3>${esc(t.title)}</h3><p>${esc(t.stage)}</p><p>${t.subject==='Reading'?'An original passage with evidence-based comprehension questions.':'Multiple-choice practice with a hint and a worked explanation for each question.'}</p></article>`).join('')}</div><p class="footnote">Starter library: ${data.topics.reduce((s,t)=>s+t.count,0)} questions across ${data.topics.length} topics. Teachers select suitability; this is not a complete GCSE specification.</p>`}
function createPage(){const tomorrow=new Date(Date.now()+7*86400000);tomorrow.setHours(16,0,0,0);const local=new Date(tomorrow-tomorrow.getTimezoneOffset()*60000).toISOString().slice(0,16);return head('Build their next step.','Pick a class and topics. OneHome selects a balanced mix of questions.')+`<form class="card" id="createForm"><div class="form-grid"><div><label for="title">Homework title</label><input id="title" maxlength="150" placeholder="e.g. Week 3 · Building confidence" required></div><div><label for="subject">Topic subject</label><select id="subject"><option>Maths</option><option>Reading</option><option>Science</option></select></div><div><label for="year">Filter class year</label><select id="year"><option value="">All years</option>${[7,8,9,10,11].map(y=>`<option>${y}</option>`).join('')}</select></div><div><label for="class">Assign to class</label><select id="class" required></select></div><div><label for="due">Deadline (your local time)</label><input id="due" type="datetime-local" value="${local}" required></div><div><label for="count">Number of questions</label><input id="count" type="number" min="1" max="40" value="5" required></div></div><label>Choose topics</label><p class="hint">At least one question from each selected topic. Select up to 12 topics from the same subject.</p><div id="topicChoices" class="topics"></div><p id="selectionCount" class="hint"></p><div class="notice">The assignment follows current MIS class membership. Save student or class changes in OneEducation, then refresh here. Students use their existing private codes.</div><button type="submit">Generate & publish homework →</button><p class="hint">Publishing makes this homework available immediately in OneHome.</p></form>`}
function reportPage(){const a=data.assignments.find(x=>x.id===reportId);if(!a)return empty('Homework not found.');const roster=data.students.filter(s=>s.classIds.includes(a.class_id)),submitted=roster.map(s=>progress(a.id,s.id)).filter(p=>p?.submitted_at),avg=submitted.length?Math.round(submitted.reduce((n,p)=>n+p.score,0)/submitted.length/a.question_ids.length*100)+'%':'—';return head(esc(a.title),`${esc(cls(a.class_id))} · Due ${date(a.due_at)}`,`<button class="secondary" id="export">Export results CSV</button>`)+stats([['Submitted',`${submitted.length} / ${roster.length}`],['Average score',avg],['Questions',a.question_ids.length]])+`<article class="card table-wrap"><table><thead><tr><th>Student</th><th>Status</th><th>Score</th><th>Submitted</th></tr></thead><tbody>${roster.map(s=>{const p=progress(a.id,s.id);return `<tr><td>${esc(name(s))}</td><td>${p?.submitted_at?(new Date(p.submitted_at)>new Date(a.due_at)?'Completed late':'Completed'):p?'In progress':due(a)?'Overdue · not started':'Not started'}</td><td>${p?.submitted_at?`${p.score} / ${a.question_ids.length}`:'—'}</td><td>${p?.submitted_at?date(p.submitted_at):'—'}</td></tr>`}).join('')}</tbody></table></article><p class="footnote">Only current, active class members are shown. Past submissions are retained when a student moves classes.</p>`}
function questionPage(){const a=active.assignment,total=active.questions.length,done=!!active.submitted_at,q=active.questions[qn];if(confirmSubmit&&!done)return head('One last check.','Once submitted, your answers are locked and your feedback is revealed.')+`<article class="card qcard"><h2>${esc(a.title)}</h2><p>${Object.keys(active.answers).length} of ${total} questions answered.</p><p>You can go back to check your answers, or submit now for your score and explanations.</p><div class="qnav"><button class="secondary" id="backQuestions">Check my answers</button><button id="finalSubmit">Submit for marking</button></div></article>`;
return head(done?'Your effort. Your progress.':esc(a.title),done?'Review each question and learn from the explanations.':`Due ${date(a.due_at)} · Your progress is saved when you move between questions.`)+`<article class="card qcard">${done?`<span class="tag done">Homework completed</span><div class="result-score">${active.score}<span class="muted" style="font-size:26px"> / ${total}</span></div>`:''}<div class="card-head"><span class="tag">${esc(q.topicTitle)}</span><small>Question ${qn+1} of ${total}</small></div><div class="bar"><span style="width:${100*(qn+1)/total}%"></span></div><div class="qnums">${active.questions.map((x,i)=>`<button data-q="${i}" class="${i===qn?'current':Object.hasOwn(active.answers,x.id)?'answered':''}" aria-label="Question ${i+1}">${i+1}</button>`).join('')}</div>${q.passage?`<div class="passage">${esc(q.passage)}</div>`:''}<h2 class="question-title">${esc(q.prompt)}</h2><div class="choices">${q.choices.map((c,i)=>`<label class="choice"><input type="radio" name="answer" value="${i}" ${active.answers[q.id]===i?'checked':''} ${done?'disabled':''}><span>${esc(c)}</span></label>`).join('')}</div>${done?`<div class="feedback"><strong class="${active.answers[q.id]===q.correct?'correct':'wrong'}">${active.answers[q.id]===q.correct?'Correct — well done.':'Keep building this skill.'}</strong><br>Correct answer: ${esc(q.choices[q.correct])}<br>${esc(q.explanation)}</div>`:`<details><summary>Need a hint?</summary><p class="hint">${esc(q.hint)}</p></details><p class="hint" id="saveStatus">${dirty?'Unsaved answer':'Progress saved when you leave this question'}</p>`}<div class="qnav"><button class="secondary" id="previous" ${qn===0?'disabled':''}>← Previous</button>${done?'':`<button class="plain" id="saveExit">Save & exit</button>`}${qn<total-1?'<button id="next">Next question →</button>':done?'<button id="finishReview">Back to results</button>':'<button id="reviewSubmit">Review & submit →</button>'}</div></article>`;}
async function saveDraft(){if(!dirty||active.submitted_at)return;active=await rpc('oh_save',{p_code:code,p_id:active.assignment.id,p_answers:active.answers,p_submit:false});dirty=false;const row={assignment_id:active.assignment.id,student_id:data.student.id,submitted_at:active.submitted_at,score:active.score};data.progress=data.progress.filter(p=>p.assignment_id!==row.assignment_id);data.progress.push(row)}
function bind(){
document.querySelectorAll('[data-create]').forEach(b=>b.onclick=()=>{view='create';render()});
document.querySelectorAll('[data-report]').forEach(b=>b.onclick=()=>{reportId=b.dataset.report;view='report';render()});
document.querySelectorAll('[data-archive]').forEach(b=>b.onclick=()=>{if(confirm('Archive this homework? It will disappear from student lists. Existing results will be kept.'))run(b,async()=>{await rpc('oh_archive',{p_id:b.dataset.archive},true);await refresh();toast('Homework archived.')})});
document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>run(b,async()=>{active=await rpc('oh_open',{p_code:code,p_id:b.dataset.open});qn=0;dirty=false;confirmSubmit=false;render()}));
const subject=document.querySelector('#topicSubject');if(subject)subject.onchange=()=>{topicSubject=subject.value;render()};const input=document.querySelector('#topicSearch');if(input)input.oninput=()=>{search=input.value;const pos=input.selectionStart;render();const f=document.querySelector('#topicSearch');f.focus();f.setSelectionRange(pos,pos)};
if(document.querySelector('#createForm'))bindCreate();
document.querySelector('#export')?.addEventListener('click',exportResults);
document.querySelectorAll('[name=answer]').forEach(r=>r.onchange=()=>{active.answers[active.questions[qn].id]=Number(r.value);dirty=true;document.querySelector('#saveStatus').textContent='Answer selected · not saved yet';});
const move=async i=>{await saveDraft();qn=i;render()};
document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>run(b,()=>move(Number(b.dataset.q))));
document.querySelector('#previous')?.addEventListener('click',e=>run(e.currentTarget,()=>move(qn-1)));
document.querySelector('#next')?.addEventListener('click',e=>run(e.currentTarget,()=>move(qn+1)));
document.querySelector('#saveExit')?.addEventListener('click',e=>run(e.currentTarget,async()=>{await saveDraft();active=null;view='homework';await refresh();toast('Your answers are saved.')}));
document.querySelector('#reviewSubmit')?.addEventListener('click',e=>run(e.currentTarget,async()=>{await saveDraft();const missing=active.questions.findIndex(q=>!Object.hasOwn(active.answers,q.id));if(missing>=0){qn=missing;render();toast('Answer every question before submitting.');return}confirmSubmit=true;render()}));
document.querySelector('#backQuestions')?.addEventListener('click',()=>{confirmSubmit=false;render()});
document.querySelector('#finalSubmit')?.addEventListener('click',e=>run(e.currentTarget,async()=>{active=await rpc('oh_save',{p_code:code,p_id:active.assignment.id,p_answers:active.answers,p_submit:true});dirty=false;confirmSubmit=false;qn=0;const row={assignment_id:active.assignment.id,student_id:data.student.id,submitted_at:active.submitted_at,score:active.score};data.progress=data.progress.filter(p=>p.assignment_id!==row.assignment_id);data.progress.push(row);render()}));
document.querySelector('#finishReview')?.addEventListener('click',e=>run(e.currentTarget,async()=>{active=null;view='completed';await refresh()}));
}
function bindCreate(){const by=id=>document.getElementById(id);const classes=()=>{const rows=data.classes.filter(c=>!by('year').value||String(c.year)===by('year').value).sort((a,b)=>a.name.localeCompare(b.name));by('class').innerHTML='<option value="">Choose a class…</option>'+rows.map(c=>`<option value="${esc(c.id)}">${esc(c.name)} (${data.students.filter(p=>p.classIds.includes(c.id)).length} students)</option>`).join('')};const count=()=>{const chosen=[...document.querySelectorAll('[name=topic]:checked')].map(x=>x.value),n=data.topics.filter(t=>chosen.includes(t.id)).reduce((a,t)=>a+t.count,0);by('selectionCount').textContent=`${chosen.length} topics selected · ${n} questions available`;};const topics=()=>{by('topicChoices').innerHTML=data.topics.filter(t=>t.subject===by('subject').value).map(t=>`<label class="topic"><input type="checkbox" name="topic" value="${esc(t.id)}"><span>${esc(t.title)}<small>${esc(t.stage)} · ${t.count} questions</small></span></label>`).join('');document.querySelectorAll('[name=topic]').forEach(x=>x.onchange=count);count()};by('year').onchange=classes;by('subject').onchange=topics;classes();topics();by('createForm').onsubmit=e=>{e.preventDefault();run(e.submitter,async()=>{const chosen=[...document.querySelectorAll('[name=topic]:checked')].map(x=>x.value);if(!chosen.length)throw Error('Select at least one topic.');const id=await rpc('oh_create',{p_class:by('class').value,p_title:by('title').value.trim(),p_topics:chosen,p_count:Number(by('count').value),p_due:new Date(by('due').value).toISOString()},true);view='homework';await refresh();toast('Homework generated and published to OneHome.');})}}
function exportResults(){const a=data.assignments.find(x=>x.id===reportId),rows=[['Student','Class','Status','Score','Total','Submitted UTC'],...data.students.filter(s=>s.classIds.includes(a.class_id)).map(s=>{const p=progress(a.id,s.id);return[name(s),cls(a.class_id),p?.submitted_at?'Completed':p?'In progress':'Not started',p?.score??'',a.question_ids.length,p?.submitted_at||'']})];const csv=rows.map(r=>r.map(v=>'"'+String(v).replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='OneHome-results.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),2000)}
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
const easyParams=new URLSearchParams(location.search);let easyContext;try{easyContext=JSON.parse(sessionStorage.getItem('oneeasy-context')||'null')}catch{}const easyReady=easyParams.get('oneeasy')==='1'&&easyContext?.school===easyParams.get('school')&&Date.now()-easyContext.created<3600000;
if(easyReady){mode=easyContext.mode==='staff'?'staff':'student';code=mode==='student'?sessionStorage.getItem('onehome-code')||'':'';if(mode==='staff'||code)refresh().catch(e=>login(e.message));else login()}else login();
